/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ndk_n_ServerDataHelper */

#ifndef _Included_com_ndk_n_ServerDataHelper
#define _Included_com_ndk_n_ServerDataHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ndk_n_ServerDataHelper
 * Method:    getDataFromServer
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ndk_n_ServerDataHelper_getDataFromServer
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
