/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ndk_n_LocalDataHelper */

#ifndef _Included_com_ndk_n_LocalDataHelper
#define _Included_com_ndk_n_LocalDataHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ndk_n_LocalDataHelper
 * Method:    getDataFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ndk_n_LocalDataHelper_getDataFromNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
