/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ndk_n_NativeRunTime */

#ifndef _Included_com_ndk_n_NativeRunTime
#define _Included_com_ndk_n_NativeRunTime
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ndk_n_NativeRunTime
 * Method:    startActivity
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ndk_n_NativeRunTime_startActivity
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_ndk_n_NativeRunTime
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ndk_n_NativeRunTime_stringFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_ndk_n_NativeRunTime
 * Method:    startService
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ndk_n_NativeRunTime_startService
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_ndk_n_NativeRunTime
 * Method:    findProcess
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_ndk_n_NativeRunTime_findProcess
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_ndk_n_NativeRunTime
 * Method:    stopService
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ndk_n_NativeRunTime_stopService
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
